#!/bin/bash
# Setup a proxy port from a remote host and port to
# localhost:30650 (the pachd port when using pachctl port-forward).


if [ -z "$1" ]; then
   echo "$0 Usage: {hostname} [PORT]"
   exit 1
fi 

MASTER_PORT=8090
if [ ! -z "$2" ]; then
MASTER_PORT=$2
fi
MASTER_HOST=$1
ssh -NR ${MASTER_HOST}:${MASTER_PORT}:localhost:30650 ${MASTER_HOST}
