apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secret
stringData:
  det_master: casablanca-login.us.cray.com:443
  det_user: harrow
  det_password: 
  pac_master: casablanca-login
  pac_port: "8090"
  pac_token: PACHYDERM_TOKEN
  sel_url: https://SELDON_HOST
  sel_secret: sd-api-secret
  sel_namespace: seldon
